name: Upload to Maestro Cloud (Native Android)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  maestro-cloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mobile-dev-inc/action-maestro-cloud@v1.1.0
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: app/build/outputs/apk/debug/MyDemo.apk
